export const sagaActions = {
  FETCH_DEVICES: "FETCH_DEVICES",
  ADD_NEW_DEVICE: "ADD_NEW_DEVICE",
  DELETE_DEVICE: "DELETE_DEVICE",
  EDIT_DEVICE: "EDIT_DEVICE",
  FAILED: "FAILED",
  CLEAR_FAIL: "CLEAR_FAIL",
  CHANGE_PAGE: "CHANGE_PAGE",
};
